#!/bin/sh
kmdUrl="https://github.com/zerofancy/kmdblog/releases/latest/download/kmdblog-fat.jar"
kmdJar="./kmdblog-fat.jar"

echo "检查更新……"
curl -L "$kmdUrl.md5">"$kmdJar.md5"
md5sum -c "$kmdJar.md5"|grep -E "OK|成功"
if [ $? -ne 0 ]; then
    echo "正在更新……"
    curl -L "$kmdUrl">"$kmdJar"
fi
java -jar "$kmdJar" "$@"
